### 摘要

* numpy里面的一些内置的方法，函数以及numpy的基本运算

ufunc参考:[http://docs.scipy.org/doc/numpy/reference/ufuncs.html](http://docs.scipy.org/doc/numpy/reference/ufuncs.html)

In [2]:
#首先导入numpy
import numpy as np

In [8]:
#首先是numpy的基本运算，如加减乘除
arr1 = np.arange(10)
print arr1
arr2 = np.arange(1,20,2)
print arr2
print "-------------"
print arr1 + arr2
print arr1 * arr2
print arr1 / arr2
print arr1 - arr2

[0 1 2 3 4 5 6 7 8 9]
[ 1  3  5  7  9 11 13 15 17 19]
-------------
[ 1  4  7 10 13 16 19 22 25 28]
[  0   3  10  21  36  55  78 105 136 171]
[0 0 0 0 0 0 0 0 0 0]
[ -1  -2  -3  -4  -5  -6  -7  -8  -9 -10]


#### 这里我们会讲解一些还算常用的ufunc

In [11]:
#max,min
arr = np.arange(10)
print arr
print arr.max()
print arr.min()

[0 1 2 3 4 5 6 7 8 9]
9
0


In [14]:
#all,any
lis1 = [1,0,3,5,False]
lis2 = [1,2,3,4]

arr1 = np.array(lis1)
arr2 = np.array(lis2)
print arr1
print arr2
print "------------"
print arr1.all()
print arr.any()

[1 0 3 5 0]
[1 2 3 4]
------------
False
True


In [16]:
#sqrt,exp
arr1 = np.arange(10)
print arr1
print "------------"
print np.sqrt(arr1)
print np.exp(arr1)

[0 1 2 3 4 5 6 7 8 9]
------------
[ 0.          1.          1.41421356  1.73205081  2.          2.23606798
  2.44948974  2.64575131  2.82842712  3.        ]
[  1.00000000e+00   2.71828183e+00   7.38905610e+00   2.00855369e+01
   5.45981500e+01   1.48413159e+02   4.03428793e+02   1.09663316e+03
   2.98095799e+03   8.10308393e+03]


In [3]:
#unique,sort
lis1 = [11,22,3,4,5,2,3,4,4,3]
arr = np.array(lis1)
print arr
print "-------------"
print np.unique(arr)
arr.sort()
print arr
print set(lis1)

[11 22  3  4  5  2  3  4  4  3]
-------------
[ 2  3  4  5 11 22]
[ 2  3  3  3  4  4  4  5 11 22]
set([2, 3, 4, 5, 11, 22])
