## 摘要

* 怎么创建数组？

这一节我们主要讲怎么创建数组(ndarray)，创建数组的方式总得来说就是两种。

1. 通过numpy自有的函数创建
2. 通过序列化数据创建数组

In [5]:
#首先导入numpy
import numpy as np

In [6]:
#np.arange 
##通过arange我们可以创建指定起始位置，终点位置，步长的一维数组
arr1 = np.arange(10)
arr2 = np.arange(1,11)
arr3 = np.arange(1,11,2)
print arr1
print arr2
print arr3


[0 1 2 3 4 5 6 7 8 9]
[ 1  2  3  4  5  6  7  8  9 10]
[1 3 5 7 9]


In [4]:
lis1 = range(10)
print lis1

np.arange(10)

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]


array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [5]:
#np.random,np.random.rand,np.random.randn
##通过random，我们可以生成指定数量的随机值
arr4 = np.random.randint(10)
arr5 = np.random.randint(1,10)
arr6 = np.random.randint(1,10,10)
print arr4
print arr5
print arr6
np.random.randint

9
6
[5 1 7 1 9 8 6 9 3 4]


In [10]:
#list
###我们可以通过序列创建数组，比如列表
lis1 = [1,2,3,4,5,6]
arr7 = np.array(lis1)
print arr7
arr8 = np.array(list("123456789"))
print arr8

[1 2 3 4 5 6]
['1' '2' '3' '4' '5' '6' '7' '8' '9']
